export type Spirit = {
  id: number;
  name: string;
  category: 'Tequila' | 'Mezcal' | 'Whisky' | 'Ron' | 'Ginebra' | 'Vermouth' | 'Seltzer' | 'Vodka' | 'Spirit' | 'Liqueur' | 'Brandy' | 'Cocktail';
  brand: string;
  origin: string;
  tastingNotes: string;
  imageUrl: string;
};

export type Brand = {
  name: string;
  logoUrl: string;
};

export type TeamMember = {
  name: string;
  role: string;
  imageUrl: string;
};

export const spirits: Spirit[] = [
  // Existing data (with some potential updates from PDFs)
  {
    id: 1,
    name: 'Gin MG',
    category: 'Ginebra',
    brand: 'Gin MG',
    origin: 'España',
    tastingNotes: "Reflejo de la herencia de elaboración de ginebra de España, elaborada desde 1940 por Manuel Giró, mostrando calidad artesanal y armonía botánica.",
    imageUrl: 'https://placehold.co/600x800.png',
  },
  {
    id: 2,
    name: 'Tovaritch Vodka',
    category: 'Vodka',
    brand: 'Tovaritch!',
    origin: 'Rusia',
    tastingNotes: "Arraigado en una receta noble desde la era de la emperatriz Catalina II, muestra la excelencia del vodka de Rusia.",
    imageUrl: 'https://placehold.co/600x800.png',
  },
  {
    id: 3,
    name: 'Kensei Blended Whisky',
    category: 'Whisky',
    brand: 'Kensei',
    origin: 'Japón',
    tastingNotes: "Aroma a flores, frutos secos y toques de barrica. En boca es afrutado, con toques de caramelo, especias y un sutil toque de vainilla. Final largo y equilibrado.",
    imageUrl: 'https://placehold.co/600x800.png',
  },
  {
    id: 4,
    name: 'Zaya Gran Reserva',
    category: 'Ron',
    brand: 'Zaya',
    origin: 'Trinidad y Tobago',
    tastingNotes: "Zaya Gran Reserva realza los cócteles con su perfil añejo, suave y aromático.",
    imageUrl: 'https://placehold.co/600x800.png',
  },
  {
    id: 5,
    name: 'Saints Hard Seltzer Mango',
    category: 'Seltzer',
    brand: 'Saints',
    origin: 'México',
    tastingNotes: "Aroma a mango fresco y dulce con un toque cítrico. En boca es suave y jugoso con un final refrescante y brillante.",
    imageUrl: 'https://placehold.co/600x800.png',
  },
  {
    id: 6,
    name: 'Templeton Rye',
    category: 'Whisky',
    brand: 'Templeton',
    origin: "Iowa, USA",
    tastingNotes: "Templeton Rye presenta whiskies premium arraigados en las ricas tradiciones de Iowa.",
    imageUrl: 'https://placehold.co/600x800.png',
  },
  {
    id: 7,
    name: 'Otto\'s Athens Vermouth',
    category: 'Vermouth',
    brand: 'Otto\'s',
    origin: 'Grecia',
    tastingNotes: "El vermut Otto's Athens está elaborado con vino griego y productos botánicos para un sabor distintivo.",
    imageUrl: 'https://placehold.co/600x800.png',
  },
  // New Products from PDFs
  {
    id: 8,
    name: 'Tequila Corralejo Silver',
    category: 'Tequila',
    brand: 'Corralejo',
    origin: 'Guanajuato, México',
    tastingNotes: 'Aroma a pimienta blanca y rosa con menta. En boca, notas de agave y hierbabuena dulce. Final ligero y fresco.',
    imageUrl: 'https://placehold.co/600x800.png',
  },
  {
    id: 9,
    name: 'Tequila Corralejo Reposado',
    category: 'Tequila',
    brand: 'Corralejo',
    origin: 'Guanajuato, México',
    tastingNotes: 'Aroma a vainilla dulce, miel, especias y toques de roble. En boca, notas de lima-limón, miel, roble y agave. Final suave y cálido.',
    imageUrl: 'https://placehold.co/600x800.png',
  },
  {
    id: 10,
    name: 'Tequila Corralejo Añejo',
    category: 'Tequila',
    brand: 'Corralejo',
    origin: 'Guanajuato, México',
    tastingNotes: 'Aroma a notas dulces de café y frutos secos. En boca es sedoso con un intenso sabor a madera y tonos ahumados. Final lujoso y con cuerpo.',
    imageUrl: 'https://placehold.co/600x800.png',
  },
  {
    id: 11,
    name: 'Los Arango Tequila Blanco',
    category: 'Tequila',
    brand: 'Los Arango',
    origin: 'México',
    tastingNotes: 'Aroma a agave tostado y hierbas verdes. En boca es suave y liso. Final fresco y brillante.',
    imageUrl: 'https://placehold.co/600x800.png',
  },
  {
    id: 12,
    name: 'Los Arango Tequila Reposado',
    category: 'Tequila',
    brand: 'Los Arango',
    origin: 'México',
    tastingNotes: 'Aroma a pimienta blanca, agave, caramelo, limón y roble suave. En boca es sedoso y elegante con notas de pimienta, agave meloso y salinidad. Final medio-largo y seco.',
    imageUrl: 'https://placehold.co/600x800.png',
  },
  {
    id: 13,
    name: 'Los Arango Tequila Añejo',
    category: 'Tequila',
    brand: 'Los Arango',
    origin: 'México',
    tastingNotes: 'Aroma a caramelo especiado y roble. En boca es rico en vainilla, pimiento verde y salinidad. Final largo, rico y especiado.',
    imageUrl: 'https://placehold.co/600x800.png',
  },
  {
    id: 14,
    name: 'Los Arango Licor de Tequila',
    category: 'Liqueur',
    brand: 'Los Arango',
    origin: 'México',
    tastingNotes: 'Aroma a agave cocido dulce y toques suaves. Sabor cremoso, dulce y sutil con un cuerpo notable y un final aterciopelado.',
    imageUrl: 'https://placehold.co/600x800.png',
  },
  {
    id: 15,
    name: 'Los Arango Coffee Liqueur',
    category: 'Liqueur',
    brand: 'Los Arango',
    origin: 'México',
    tastingNotes: 'Aroma a granos de café tostado, caramelo y un ligero toque de agave ahumado. Sabor intenso a café con una ligera nota de agave, cremoso y dulce.',
    imageUrl: 'https://placehold.co/600x800.png',
  },
  {
    id: 16,
    name: 'Corralejo Extra Añejo',
    category: 'Tequila',
    brand: 'Corralejo',
    origin: 'Guanajuato, México',
    tastingNotes: 'Aroma a caramelo oscuro dulce y especias cálidas. En boca, roble, ligero humo, cítricos con toques de azúcar moreno y agave. Final redondo y con cuerpo.',
    imageUrl: 'https://placehold.co/600x800.png',
  },
  {
    id: 17,
    name: 'Gran Corralejo Tequila Añejo',
    category: 'Tequila',
    brand: 'Gran Corralejo',
    origin: 'México',
    tastingNotes: 'Aroma a tonos ricos combinados con notas amaderadas de chocolate, vainilla y nuez. Final sedoso con tonos dulces y un persistente sabor a madera.',
    imageUrl: 'https://placehold.co/600x800.png',
  },
  {
    id: 18,
    name: '99,000 Horas Añejo',
    category: 'Tequila',
    brand: '99,000 Horas',
    origin: 'Guanajuato, México',
    tastingNotes: 'Aromas a chocolate, vainilla y almendra con intensos aromas de roble. Final sedoso y con cuerpo que entrega intensas notas de madera y chocolate.',
    imageUrl: 'https://placehold.co/600x800.png',
  },
  {
    id: 19,
    name: 'Mezcal Espanta Espiritus',
    category: 'Mezcal',
    brand: 'Espanta Espiritus',
    origin: 'San Luis Potosí, México',
    tastingNotes: 'Aroma a agave cocido y notas ahumadas, con acentos de hierbas frescas y cítricos. Sabor a agave cocido, ahumado y dulce, combinado con la frescura de manzanas verdes.',
    imageUrl: 'https://placehold.co/600x800.png',
  },
  {
    id: 20,
    name: 'Ron Prohibido Silver',
    category: 'Ron',
    brand: 'Ron Prohibido',
    origin: 'México',
    tastingNotes: 'Aromas suaves y dulces de anís, rosa, manzana y pasas. Sabor sedoso con un equilibrio entre el amargor cítrico y la dulzura de la caña de azúcar.',
    imageUrl: 'https://placehold.co/600x800.png',
  },
  {
    id: 21,
    name: 'Ron Prohibido Reserva 12',
    category: 'Ron',
    brand: 'Ron Prohibido',
    origin: 'México',
    tastingNotes: 'Aroma a madera dulce y pasas. Sabor a pasas y ciruelas con toques de chocolate y café. Final largo y sedoso con acentos de vainilla y caramelo.',
    imageUrl: 'https://placehold.co/600x800.png',
  },
  {
    id: 22,
    name: 'Ley Seca Mexican Whisky',
    category: 'Whisky',
    brand: 'Ley Seca',
    origin: 'México',
    tastingNotes: 'Aroma a cebada, frutas sutiles, nueces, manzana amarilla, vainilla y roble. Sabor a malta, vainilla y fruta con un sutil ahumado. Final prolongado y suave.',
    imageUrl: 'https://placehold.co/600x800.png',
  },
  {
    id: 23,
    name: 'Horus Licor de Chocolate',
    category: 'Liqueur',
    brand: 'Horus',
    origin: 'México',
    tastingNotes: 'Aroma a chocolate en fusión con cacao y la suavidad de la vainilla. Sabor a chocolate, cacao y vainilla en una combinación perfecta y cremosa.',
    imageUrl: 'https://placehold.co/600x800.png',
  },
  {
    id: 24,
    name: 'Vodka Boker',
    category: 'Vodka',
    brand: 'Boker',
    origin: 'México',
    tastingNotes: 'Aroma a esencia pura de grano de maíz con un delicado toque de dulzura. En boca es refinado y adaptable, ideal como base en cócteles.',
    imageUrl: 'https://placehold.co/600x800.png',
  },
  {
    id: 25,
    name: 'Brandy Tres Cepas',
    category: 'Brandy',
    brand: 'Tres Cepas',
    origin: 'México',
    tastingNotes: 'Perfil afrutado y dulce con notas de caramelo, vainilla, coco, chocolate y uvas. Final persistente con notas de frutos secos, madera y un toque de pimienta.',
    imageUrl: 'https://placehold.co/600x800.png',
  },
  {
    id: 26,
    name: 'Conde de Cuba 3 Años',
    category: 'Ron',
    brand: 'Conde de Cuba',
    origin: 'Cuba',
    tastingNotes: 'Aroma suave, herbal, con notas ligeras y delicadas de roble. En boca es suave y ofrece aromas de vainilla con toques de cáscara de naranja.',
    imageUrl: 'https://placehold.co/600x800.png',
  },
  {
    id: 27,
    name: 'Conde de Cuba 5 Años',
    category: 'Ron',
    brand: 'Conde de Cuba',
    origin: 'Cuba',
    tastingNotes: 'Aroma a naranja, notas florales y toques de roble ahumado. En boca es suave con aromas de vainilla y toques de cáscara de naranja.',
    imageUrl: 'https://placehold.co/600x800.png',
  },
  {
    id: 28,
    name: 'Enzo Japanese Whisky',
    category: 'Whisky',
    brand: 'Enzo',
    origin: 'Japón',
    tastingNotes: 'Aroma floral ligero con toques de manzana, cítricos y vainilla. En boca es suave con notas de caramelo, canela y roble dulce. Final medio con vainilla persistente.',
    imageUrl: 'https://placehold.co/600x800.png',
  },
  {
    id: 29,
    name: 'Guerrero Maya Espadin Joven',
    category: 'Mezcal',
    brand: 'Guerrero Maya',
    origin: 'Oaxaca, México',
    tastingNotes: 'Sabores fuertes y ahumados con un gusto limpio y fresco. Ideal con postres de vainilla o chocolate negro.',
    imageUrl: 'https://placehold.co/600x800.png',
  },
  {
    id: 30,
    name: 'Guerrero Maya Espadin Reposado',
    category: 'Mezcal',
    brand: 'Guerrero Maya',
    origin: 'Oaxaca, México',
    tastingNotes: 'Aromas de madera cálida y agave cocido. Sutiles toques de avellana tostada y vainilla. Final suave y persistente.',
    imageUrl: 'https://placehold.co/600x800.png',
  },
  {
    id: 31,
    name: 'Nobushi Blended Whisky',
    category: 'Whisky',
    brand: 'Nobushi',
    origin: 'Japón',
    tastingNotes: 'Aroma a flores, frutas frescas y especias. Sabor afrutado y con cuerpo, con especias combinadas con caramelo y vainilla.',
    imageUrl: 'https://placehold.co/600x800.png',
  },
  {
    id: 32,
    name: 'Yuuvi Citrus Mezcal Cocktail',
    category: 'Cocktail',
    brand: 'Yuuvi',
    origin: 'Oaxaca, México',
    tastingNotes: 'Una revolución de sabor con una infusión de terpenos naturales. Sabores intensos a cereza negra, maracuyá, mango, lima y cítricos.',
    imageUrl: 'https://placehold.co/600x800.png',
  },
  {
    id: 33,
    name: 'Quita Penas Tequila Blanco',
    category: 'Tequila',
    brand: 'Quita Penas',
    origin: 'Guanajuato, México',
    tastingNotes: 'Aromas florales y afrutados suaves y una nota ligeramente dulce de agave cocido. Sabor a menta refrescante, notas de lima y un rastro de agave cocido. Final fresco y sedoso.',
    imageUrl: 'https://placehold.co/600x800.png',
  },
  {
    id: 34,
    name: 'Quita Penas Tequila Reposado',
    category: 'Tequila',
    brand: 'Quita Penas',
    origin: 'Guanajuato, México',
    tastingNotes: 'Tonos herbales combinados con notas de agave. Tequila con un intenso carácter herbal que deja un dulzor y notas ligeras en el paladar.',
    imageUrl: 'https://placehold.co/600x800.png',
  },
];

export const brands: Brand[] = [
  { name: 'Corralejo', logoUrl: 'https://placehold.co/200x100.png' },
  { name: 'Gran Corralejo', logoUrl: 'https://placehold.co/200x100.png' },
  { name: '99,000 Horas', logoUrl: 'https://placehold.co/200x100.png' },
  { name: 'Los Arango', logoUrl: 'https://placehold.co/200x100.png' },
  { name: 'Espanta Espiritus', logoUrl: 'https://placehold.co/200x100.png' },
  { name: 'Ron Prohibido', logoUrl: 'https://placehold.co/200x100.png' },
  { name: 'Reserva 22', logoUrl: 'https://placehold.co/200x100.png' },
  { name: 'Ley Seca', logoUrl: 'https://placehold.co/200x100.png' },
  { name: 'Horus', logoUrl: 'https://placehold.co/200x100.png' },
  { name: 'Quita Penas', logoUrl: 'https://placehold.co/200x100.png' },
  { name: 'Boker', logoUrl: 'https://placehold.co/200x100.png' },
  { name: 'Tres Cepas', logoUrl: 'https://placehold.co/200x100.png' },
  { name: 'Kensei', logoUrl: 'https://placehold.co/200x100.png' },
  { name: 'Templeton', logoUrl: 'https://placehold.co/200x100.png' },
  { name: 'Conde de Cuba', logoUrl: 'https://placehold.co/200x100.png' },
  { name: 'Zaya', logoUrl: 'https://placehold.co/200x100.png' },
  { name: 'Carlo Alberto', logoUrl: 'https://placehold.co/200x100.png' },
  { name: 'Otto\'s', logoUrl: 'https://placehold.co/200x100.png' },
  { name: 'Gin MG', logoUrl: 'https://placehold.co/200x100.png' },
  { name: 'Saints', logoUrl: 'https://placehold.co/200x100.png' },
  { name: 'Nobushi', logoUrl: 'https://placehold.co/200x100.png' },
  { name: 'Tovaritch!', logoUrl: 'https://placehold.co/200x100.png' },
  { name: 'Guerrero Maya', logoUrl: 'https://placehold.co/200x100.png' },
  { name: 'Chilcuague', logoUrl: 'https://placehold.co/200x100.png' },
  { name: 'Seventeen', logoUrl: 'https://placehold.co/200x100.png' },
  { name: 'Skinos', logoUrl: 'https://placehold.co/200x100.png' },
  { name: 'Enzo', logoUrl: 'https://placehold.co/200x100.png' },
  { name: 'Macho Silvestre', logoUrl: 'https://placehold.co/200x100.png' },
  { name: 'Perro de San Juan', logoUrl: 'https://placehold.co/200x100.png' },
  { name: 'Yukisato', logoUrl: 'https://placehold.co/200x100.png' },
  { name: 'Yuuvi', logoUrl: 'https://placehold.co/200x100.png' },
];

export const team: TeamMember[] = [
  {
    name: 'Juan Pérez',
    role: 'Director General',
    imageUrl: 'https://placehold.co/400x400.png',
  },
  {
    name: 'María García',
    role: 'Directora de Marcas',
    imageUrl: 'https://placehold.co/400x400.png',
  },
  {
    name: 'Carlos Rodríguez',
    role: 'Gerente de Ventas',
    imageUrl: 'https://placehold.co/400x400.png',
  },
];

export const spiritCategories = ['Tequila', 'Mezcal', 'Whisky', 'Ron', 'Ginebra', 'Vermouth', 'Seltzer', 'Vodka', 'Spirit', 'Liqueur', 'Brandy', 'Cocktail'];

export const spiritBrands = [
  'Corralejo',
  'Gran Corralejo',
  '99,000 Horas',
  'Los Arango',
  'Espanta Espiritus',
  'Ron Prohibido',
  'Reserva 22',
  'Ley Seca',
  'Horus',
  'Quita Penas',
  'Boker',
  'Tres Cepas',
  'Kensei',
  'Templeton',
  'Conde de Cuba',
  'Zaya',
  'Carlo Alberto',
  'Otto\'s',
  'Gin MG',
  'Saints',
  'Nobushi',
  'Tovaritch!',
  'Guerrero Maya',
  'Chilcuague',
  'Seventeen',
  'Skinos',
  'Enzo',
  'Macho Silvestre',
  'Perro de San Juan',
  'Yukisato',
  'Yuuvi',
];
